# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: octaCI

on:
  push:
    branches: ["A01781042"]
  schedule:
    - cron: "35 17 * * 3"

jobs:
  build:
    runs-on:
      ubuntu-latest
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/A01781042
        run: npm install

      - name: Run Build
        working-directory: ${{ github.workspace }}/A01781042
        run: npm run build --if-present

  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        working-directory: ${{ github.workspace }}/A01781042
        run: |
          npm install -g eslint
          npm init @eslint/config -- --config semistandard

      - name: Run ESLint
        run: npx eslint
        continue-on-error: true

  unit-testig:
    name: Run unit testing with vitest
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install vitest
        working-directory: ${{ github.workspace }}/A01781042
        run: |
          npm install -D vitest

      - name: Run vitest
        working-directory: ${{ github.workspace }}/A01781042
        run: npm run test
        continue-on-error: true
