name: Lint Code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Install zip
        run: sudo apt-get install zip

      - name: Run ESLint
        run: npx eslint 'A01028570/src/**/**/*.js'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: npm test

  package:
    runs-on: ubuntu-latest
    steps:
      - name: Zip files
        run: npm run zip

  dockerize:
    - name: Dockerize app
    steps:
      run: make up
